# To be appended to the Gemfile generated by `rails new`

source 'https://rubygems.org'

# ImageMagick
gem 'rmagick'

group :development, :test do
  gem 'pry-rails'
  # gem 'pry-byebug'
  gem 'factory_bot_rails'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'spring-commands-rspec'
end

group :development do
  # Code analyzer
  gem 'rubocop-git', require: false
  gem 'spring-commands-rubocop'
end
